# Generated by Django 5.2.4 on 2025-07-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0002_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
